diff --git a/wcs/Makefile b/wcs/Makefile
index 2fb9890..ec2fae0 100644
--- a/wcs/Makefile
+++ b/wcs/Makefile
@@ -1,43 +1,20 @@
-# 
-CFLAGS= -w -fPIC $(arch_flags)
-OSTYPE = $(shell uname)
-ifneq ($(findstring BSD,$(OSTYPE)),)
-CC            = cc
-else
-CC            = gcc
-endif
-ifneq ($(findstring Darwin,$(OSTYPE)),)
-SO_Name       = libcdcwcs.dylib
-LIBFLAGS      = -Wl,-single_module -dynamiclib  -lc -lm -mmacosx-version-min=10.6
-else
-SOName        = libpaswcs.so.1
-SO_Name       = libpaswcs.so.1.1
-LIBFLAGS      = -shared -Wl,-soname,$(SOName) -lc -lm
-endif
-ifneq ($(findstring W32,$(OSTYPE)),)
-SO_Name       = libcdcwcs.dll
-LIBFLAGS      = -shared -Wl,-soname,$(SO_Name)  -lm
-endif
-ifneq ($(findstring MINGW,$(OSTYPE)),)
-SO_Name       = libcdcwcs.dll
-LIBFLAGS      = -shared -Wl,-soname,$(SO_Name)  -lm
-endif
+CFLAGS= -g -D_FILE_OFFSET_BITS=64
+CC= cc
 
-OBJS =	cdcwcs.o imgetwcs.o daoread.o wcscon.o \
-	fitswcs.o wcsinit.o wcs.o  \
-	imrotate.o fitsfile.o imhfile.o \
+OBJS =	imsetwcs.o imgetwcs.o matchstar.o findstar.o daoread.o wcscon.o \
+	fitswcs.o wcsinit.o wcs.o ty2read.o webread.o tmcread.o \
+	gscread.o gsc2read.o ujcread.o uacread.o ubcread.o ucacread.o \
+	sdssread.o tabread.o binread.o ctgread.o actread.o catutil.o \
+	skybotread.o imrotate.o fitsfile.o imhfile.o \
 	hget.o hput.o imio.o dateutil.o imutil.o \
 	worldpos.o tnxpos.o zpxpos.o dsspos.o platepos.o \
-	sortstar.o iget.o fileutil.o \
+	sortstar.o platefit.o iget.o fileutil.o \
 	wcslib.o lin.o cel.o proj.o sph.o wcstrig.o distort.o poly.o
-LIBS = -lm
 
-all: $(SO_Name)
+libwcs.a:	$(OBJS)
+	ar rv $@ $?
+	ranlib $@
 
-$(SO_Name): $(OBJS)
-	$(CC) $(CFLAGS) $(LIBFLAGS) -o $@ $(OBJS) $(LIBS)
-
-cdcwcs.o:	fitsfile.h wcs.h
 actread.o:	fitsfile.h wcscat.h wcs.h fitshead.h wcslib.h
 binread.o:	wcscat.h wcs.h fitshead.h wcslib.h
 ctgread.o:	wcscat.h wcs.h fitshead.h wcslib.h
@@ -90,4 +67,4 @@ webread.o:	wcscat.h
 worldpos.o:	wcs.h fitshead.h wcslib.h
 
 clean:
-	rm -f *.a *.o $(SO_Name)
+	rm -f *.a *.o
